# Form implementation generated from reading ui file 'grades.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Gradechecker(object):
    def setupUi(self, Gradechecker):
        Gradechecker.setObjectName("Gradechecker")
        Gradechecker.setEnabled(True)
        Gradechecker.resize(450, 517)
        self.centralwidget = QtWidgets.QWidget(parent=Gradechecker)
        self.centralwidget.setObjectName("centralwidget")
        self.studentLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.studentLabel.setGeometry(QtCore.QRect(10, 20, 191, 51))
        self.studentLabel.setObjectName("studentLabel")
        self.studentLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.studentLine.setGeometry(QtCore.QRect(120, 30, 201, 20))
        self.studentLine.setObjectName("studentLine")
        self.attemptsLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.attemptsLabel.setGeometry(QtCore.QRect(10, 90, 131, 41))
        self.attemptsLabel.setObjectName("attemptsLabel")
        self.numLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.numLine.setGeometry(QtCore.QRect(120, 100, 211, 20))
        self.numLine.setObjectName("numLine")
        self.gradeBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.gradeBtn.setGeometry(QtCore.QRect(130, 370, 181, 23))
        self.gradeBtn.setObjectName("gradeBtn")
        self.scoreLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.scoreLabel.setGeometry(QtCore.QRect(20, 170, 47, 13))
        self.scoreLabel.setObjectName("scoreLabel")
        self.scoreLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.scoreLine.setGeometry(QtCore.QRect(120, 170, 211, 20))
        self.scoreLine.setObjectName("scoreLine")
        self.scoreLine_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.scoreLine_2.setGeometry(QtCore.QRect(120, 210, 211, 20))
        self.scoreLine_2.setObjectName("scoreLine_2")
        self.scoreLine_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.scoreLine_3.setGeometry(QtCore.QRect(120, 260, 211, 20))
        self.scoreLine_3.setObjectName("scoreLine_3")
        self.scoreLine_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.scoreLine_4.setGeometry(QtCore.QRect(120, 300, 211, 20))
        self.scoreLine_4.setObjectName("scoreLine_4")
        self.scoreLabel_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.scoreLabel_2.setGeometry(QtCore.QRect(20, 220, 47, 13))
        self.scoreLabel_2.setObjectName("scoreLabel_2")
        self.scoreLabel_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.scoreLabel_3.setGeometry(QtCore.QRect(20, 270, 47, 13))
        self.scoreLabel_3.setObjectName("scoreLabel_3")
        self.scoreLabel_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.scoreLabel_4.setGeometry(QtCore.QRect(20, 310, 47, 13))
        self.scoreLabel_4.setObjectName("scoreLabel_4")
        self.statuslabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.statuslabel.setGeometry(QtCore.QRect(40, 420, 341, 31))
        self.statuslabel.setText("")
        self.statuslabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.statuslabel.setObjectName("statuslabel")
        Gradechecker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Gradechecker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        Gradechecker.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Gradechecker)
        self.statusbar.setObjectName("statusbar")
        Gradechecker.setStatusBar(self.statusbar)

        self.retranslateUi(Gradechecker)
        QtCore.QMetaObject.connectSlotsByName(Gradechecker)

    def retranslateUi(self, Gradechecker):
        _translate = QtCore.QCoreApplication.translate
        Gradechecker.setWindowTitle(_translate("Gradechecker", "MainWindow"))
        self.studentLabel.setText(_translate("Gradechecker", "Student name: "))
        self.attemptsLabel.setText(_translate("Gradechecker", "No of attempts: "))
        self.gradeBtn.setText(_translate("Gradechecker", "SUBMIT "))
        self.scoreLabel.setText(_translate("Gradechecker", "Score 1: "))
        self.scoreLabel_2.setText(_translate("Gradechecker", "Score 2: "))
        self.scoreLabel_3.setText(_translate("Gradechecker", "Score 3: "))
        self.scoreLabel_4.setText(_translate("Gradechecker", "Score 4: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gradechecker = QtWidgets.QMainWindow()
    ui = Ui_Gradechecker()
    ui.setupUi(Gradechecker)
    Gradechecker.show()
    sys.exit(app.exec())
